version: '3.3'

services:
    nginx:
        image: nginx:alpine
        container_name: composer-site_nginx
        ports:
            - "80:80"
            - "443:443"
        environment:
            - VIRTUAL_HOST=framework.local
        volumes:
            - ./src/:/usr/share/nginx/site
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - composer-site
    php:
        image: php:7.4.2-fpm-alpine3.11
        container_name: composer-site_php-fpm
        build:
            context: ./php
        volumes:
            - ./src/:/usr/share/nginx/site
        env_file:
          - ./src/.env
        ports:
            - "9000:9000"
        depends_on:
            - db
        networks:
            - composer-site
    db:
        image: mysql:latest
        container_name: framework-opdr_database
        restart: always
        environment:
            MYSQL_DATABASE: 'framework'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        networks:
            - composer-site

networks:
    composer-site: