version: '3.7'

services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: sql-game
        restart: always
        environment:
            MYSQL_DATABASE: 'game'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./database/:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
        expose:
            - '3306'