version: '3.3'

services:
    nginx:
        image: nginx:alpine
        container_name: cswd_eind-opdr_nginx
        ports:
            - "8081:80"
            - "443:443"
        volumes:
            - ./src/:/usr/share/nginx/site
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - cswd_eind-opdr
    php:
        image: php:7.4.2-fpm-alpine3.11
        container_name: cswd_eind-opdr_php-fpm
        build:
            context: ./php
        volumes:
            - ./src/:/usr/share/nginx/site
        ports:
            - "9000:9000"
        networks:
            - cswd_eind-opdr

networks:
    cswd_eind-opdr: